### PR TITLE
22 Fixed StringIndexOutOfBoundsException in org.mycore.mets.model.fil…

### LINKED ISSUE #22: StringIndexOutOfBoundsException in org.mycore.mets.model.files.File#asElement
<pre>
java.util.concurrent.CompletionException: java.lang.StringIndexOutOfBoundsException: begin -1, end 34, length 34
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.StringIndexOutOfBoundsException: begin -1, end 34, length 34
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at java.base/java.lang.String.substring(String.java:2677)
	at de.uni_jena.thulb.archive.media.MediaService.isMediaSupported(MediaService.java:180)
	at de.uni_jena.thulb.archive.media.events.MediaEventHandler.encodeMediaFile(MediaEventHandler.java:91)
	at de.uni_jena.thulb.archive.media.events.MediaEventHandler.lambda$handlePathCreated$2(MediaEventHandler.java:75)
	at org.mycore.util.concurrent.MCRTransactionableRunnable.run(MCRTransactionableRunnable.java:82)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
</pre>

### PR DESCRIPTION
**Pull request by Possommi**
…es.File#asElement

### CODE REVIEW

File: src/main/java/org/mycore/mets/model/files/File.java [hunk 1]
```diff
@@ -123,13 +125,13 @@ public String toString() {
...
      * (non-Javadoc)
-     * 
+     *
      * @see org.mycore.mets.model.IMetsElement#asElement()
      */
     public Element asElement() {
         Element file = new Element("file", IMetsElement.METS);
         file.setAttribute("ID", this.getId());
-        file.setAttribute("MIMETYPE", this.getMimeType());
+        file.setAttribute("MIMETYPE", Optional.ofNullable(getMimeType()).orElse("application/octet-stream"));
```
Comment (rsteph-de) [inline src/main/java/org/mycore/mets/model/files/File.java]: I would not set the default "application/octet-stream" and not add the attribute at all if the mimetype is null

File: src/main/java/org/mycore/mets/model/files/File.java [hunk 2]
```diff
@@ -2,22 +2,24 @@
...
  * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  * details.
- * 
+ *
  * You should have received a copy of the GNU General Public License along with
  * Mets-Editor. If not, see http://www.gnu.org/licenses/.
  */
 package org.mycore.mets.model.files;
 
+import java.util.Optional;
```
Comment (rsteph-de) [inline src/main/java/org/mycore/mets/model/files/File.java]: is this import still needed?

**Review by rsteph-de — APPROVED** [review]
looks goodfor me
